steps:
  test:
    image: rust:1.76-slim
    commands:
      - cargo check
      - cargo test -- --include-ignored
  build:
    when:
      event: tag
    image: rust:1.76-slim
    commands:
      - cargo build --release
  publish:
    when:
      event: tag
    image: woodpeckerci/plugin-gitea-release
    settings:
        base_url: https://git.seagle.sh
        files:
          - "target/release/permfixer"
        api_key:
          from_secret: FORGEJO_ACCESS_TOKEN
        target: main
